USE [master]
GO

/****** Object:  Database [TaxiDB]    Script Date: 02/03/2022 6:59:58 PM ******/
CREATE DATABASE [TaxiDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'TaxiDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SERVERNEW\MSSQL\DATA\TaxiDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'TaxiDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SERVERNEW\MSSQL\DATA\TaxiDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [TaxiDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [TaxiDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [TaxiDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [TaxiDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [TaxiDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [TaxiDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [TaxiDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [TaxiDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [TaxiDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [TaxiDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [TaxiDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [TaxiDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [TaxiDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [TaxiDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [TaxiDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [TaxiDB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [TaxiDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [TaxiDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [TaxiDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [TaxiDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [TaxiDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [TaxiDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [TaxiDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [TaxiDB] SET RECOVERY FULL 
GO

ALTER DATABASE [TaxiDB] SET  MULTI_USER 
GO

ALTER DATABASE [TaxiDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [TaxiDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [TaxiDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [TaxiDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [TaxiDB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [TaxiDB] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [TaxiDB] SET QUERY_STORE = OFF
GO

ALTER DATABASE [TaxiDB] SET  READ_WRITE 
GO

